// Copyright (c) Microsoft. All rights reserved.

using _15C_FullDevelopmentCopilot.Agents;
using _15C_FullDevelopmentCopilot.Services;

// ==========================================
// 15 단계 C: 통합 개발 코파일럿
// ==========================================
// 학습 목표:
// 1. 통합 개발 워크플로우
// 2. 코드/테스트/문서 자동화
// 3. 프로덕션 배포 준비
// 4. 품질 관리
// ==========================================

Console.WriteLine("🚀 통합 개발 코파일럿에 오신 것을 환영합니다!");
Console.WriteLine("요구사항부터 배포까지 자동으로 개발합니다.\n");

// 환경 변수 확인
var apiKey = Environment.GetEnvironmentVariable("OPENAI_API_KEY")
    ?? throw new InvalidOperationException("OPENAI_API_KEY 환경 변수를 설정해주세요.");

var baseUrl = Environment.GetEnvironmentVariable("OPENAI_BASE_URL")
    ?? "https://api.openai.com/v1";

Console.WriteLine($"✅ OpenAI API 키가 설정되었습니다.");
Console.WriteLine($"✅ Base URL: {baseUrl}\n");

// 서비스 및 에이전트 생성
var workflowService = new DevelopmentWorkflowService();
var qualityChecker = new CodeQualityChecker();
var devAgent = new DevelopmentAgent(apiKey, baseUrl);
var testAgent = new TestGenerationAgent(apiKey, baseUrl);
var docAgent = new DocumentationAgent(apiKey, baseUrl);
var deployAgent = new DeploymentAgent(apiKey, baseUrl);

Console.WriteLine("✅ 통합 개발 도구가 초기화되었습니다.\n");

Console.WriteLine("📋 사용 예시:");
Console.WriteLine("  - \"사용자 인증 서비스\"");
Console.WriteLine("  - \"주문 처리 시스템\"");
Console.WriteLine("  - \"결제 게이트웨이 연동\"\n");

Console.WriteLine("개발할 기능의 요구사항을 입력하세요 (종료: 'quit' 또는 'exit')\n");

while (true)
{
    Console.Write("👤 사용자: ");
    var requirement = Console.ReadLine();

    if (string.IsNullOrWhiteSpace(requirement) ||
        requirement.Equals("quit", StringComparison.OrdinalIgnoreCase) ||
        requirement.Equals("exit", StringComparison.OrdinalIgnoreCase))
    {
        Console.WriteLine("\n👋 프로그램을 종료합니다.");
        break;
    }

    try
    {
        // 프로젝트 컨텍스트 생성
        var project = new ProjectContext
        {
            ProjectName = "AutoGeneratedProject",
            FeatureName = requirement
        };

        // 워크플로우 시작
        workflowService.StartWorkflow(requirement);
        workflowService.DisplayWorkflow();

        // Stage 1: 코드 생성
        Console.WriteLine("\n✍️ Stage 1: 코드 생성 중...");
        workflowService.NextStage();
        
        project.GeneratedCode = await devAgent.DevelopFeatureAsync(requirement);
        Console.WriteLine("✅ 코드 생성 완료");
        
        // 코드 품질 검사
        var qualityReport = qualityChecker.CheckQuality(project.GeneratedCode);
        Console.WriteLine($"   품질점수: {qualityReport.OverallScore}/100 ({qualityReport.Rating})");

        // Stage 2: 테스트 생성
        Console.WriteLine("\n🧪 Stage 2: 테스트 생성 중...");
        workflowService.NextStage();
        
        project.GeneratedTests = await testAgent.GenerateTestsAsync(project.GeneratedCode);
        Console.WriteLine("✅ 테스트 생성 완료");

        // Stage 3: 코드 리뷰
        Console.WriteLine("\n📋 Stage 3: 코드 리뷰 중...");
        workflowService.NextStage();
        
        // 리뷰는 에이전트가 자동 수행 (데모)
        project.ReviewComments.Add("✅ 인터페이스 분리 적절함");
        project.ReviewComments.Add("✅ 비동기 패턴正确使用");
        project.ReviewComments.Add("⚠️ 에러 처리 보강 필요");
        Console.WriteLine("   리뷰 완료:");
        foreach (var comment in project.ReviewComments)
        {
            Console.WriteLine($"     {comment}");
        }

        // Stage 4: 문서 생성
        Console.WriteLine("\n📝 Stage 4: 문서 생성 중...");
        workflowService.NextStage();
        
        project.GeneratedDocs = await docAgent.GenerateDocumentationAsync(project.GeneratedCode, requirement);
        Console.WriteLine("✅ 문서 생성 완료");

        // Stage 5: 배포 준비
        Console.WriteLine("\n🚀 Stage 5: 배포 준비 중...");
        workflowService.NextStage();
        
        project.DeploymentPlan = await deployAgent.PrepareDeploymentAsync(requirement);
        Console.WriteLine("✅ 배포 준비 완료");
        
        project.IsProductionReady = true;
        workflowService.NextStage();

        // 최종 결과 표시
        workflowService.DisplayWorkflow();

        Console.WriteLine("\n" + new string('=', 70));
        Console.WriteLine($"🎉 개발 완료: {requirement}");
        Console.WriteLine(new string('=', 70));
        
        Console.WriteLine($"\n📁 생성된 아티팩트:");
        Console.WriteLine($"   - 소스코드: {project.GeneratedCode.Length}자");
        Console.WriteLine($"   - 테스트: {project.GeneratedTests.Length}자");
        Console.WriteLine($"   - 문서: {project.GeneratedDocs.Length}자");
        Console.WriteLine($"   - 배포계획: {project.DeploymentPlan.Length}자");
        
        Console.WriteLine($"\n📊 품질 리포트:");
        Console.WriteLine($"   - 품질점수: {qualityReport.OverallScore}/100 ({qualityReport.Rating})");
        Console.WriteLine($"   - 코드줄수: {qualityReport.LineCount}줄");
        Console.WriteLine($"   - 주석있음: {(qualityReport.HasComments ? "✅" : "❌")}");
        Console.WriteLine($"   - 비동기: {(qualityReport.HasAsync ? "✅" : "❌")}");
        Console.WriteLine($"   - 에러처리: {(qualityReport.HasErrorHandling ? "✅" : "❌")}");
        
        Console.WriteLine($"\n✅ 프로덕션 준비: {(project.IsProductionReady ? "완료" : "필요")}");
        Console.WriteLine(new string('=', 70));

        Console.WriteLine("\n생성된 코드를 확인하시겠습니까? (y/n)");
        var showCode = Console.ReadLine();
        if (showCode?.Equals("y", StringComparison.OrdinalIgnoreCase) == true)
        {
            Console.WriteLine("\n📝 생성된 코드 (미리보기):");
            Console.WriteLine(new string('-', 60));
            var lines = project.GeneratedCode.Split('\n').Take(30);
            foreach (var line in lines)
            {
                Console.WriteLine(line);
            }
            Console.WriteLine(new string('-', 60));
        }

        Console.WriteLine("\n배포 계획을 확인하시겠습니까? (y/n)");
        var showDeploy = Console.ReadLine();
        if (showDeploy?.Equals("y", StringComparison.OrdinalIgnoreCase) == true)
        {
            Console.WriteLine("\n🚀 배포 계획:");
            Console.WriteLine(project.DeploymentPlan);
        }
    }
    catch (Exception ex)
    {
        Console.WriteLine($"\n❌ 오류 발생: {ex.Message}\n");
    }
}
